pool:
  vmImage: 'ubuntu-18.04'

variables:
  - name: releaseName
    value: 'javademo'

  - name: workingDirectory
    value: '$(System.DefaultWorkingDirectory)/samples/pod_identity/java/api_kv_demo'

  - name: buildDirectory
    value: '$(System.DefaultWorkingDirectory)/samples/pod_identity/java/api_kv_demo/target'

  - name: publishedfile
    value: api_kv_demo.zip

  - name: pomFilePath
    value: '$(System.DefaultWorkingDirectory)/samples/pod_identity/java/api_kv_demo/pom.xml'


  - name: dockerFilePath
    value: '../$(releaseName)/Dockerfile'

  - name: chartFilePath
    value: '$(System.DefaultWorkingDirectory)/samples/pod_identity/java/api_kv_demo/chart'

  - name: acrServiceConnection
    value: 'dockersvc'

  - name: acrRepo
    value: 'javademo'

  - name: helmArtifactName
    value: 'javademochart'

  - name: kubernetesServiceConnection
    value: 'aks-main-demo'

  - name: namespacedemo
    value: 'demo'

  - name: buildConfiguration
    value: 'Release'

  - name: host
    value: 'ip'

stages:
- stage: javabuild
  displayName: 'Java Build & Test'
  dependsOn: []
  jobs:
  - job: build
    steps:
      - task: Maven@3
        displayName: 'Package'
        inputs:
          mavenPomFile: $(pomFilePath)
          options: '-DskipTests'
          publishJUnitResults: false


      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(workingDirectory)'
          Contents: 'Dockerfile'
          TargetFolder: '$(buildDirectory)'


      - task: PublishPipelineArtifact@1
        condition:  succeeded()
        inputs:
          targetPath: '$(buildDirectory)'
          artifact: $(releaseName)
          publishLocation: 'pipeline'

      - task: PublishPipelineArtifact@1
        condition:  succeeded()
        inputs:
          targetPath: '$(chartFilePath)'
          artifact: $(helmArtifactName)
          publishLocation: 'pipeline'


- stage: dockerbuild
  displayName: 'Docker Build'
  condition:  succeeded()
  jobs:
  - deployment: dockerbuild
    environment: dockerDemo
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: $(releaseName)

            - task: Docker@2
              displayName: Login to ACR
              inputs:
                command: login
                containerRegistry: $(acrServiceConnection)

            - task: Docker@2
              displayName: Build  image
              inputs:
                repository: $(acrRepo)
                command: build
                Dockerfile: $(dockerFilePath)
                containerRegistry: $(acrServiceConnection)
                tags: |
                  $(Build.BuildId)
                  $(Build.SourceVersion)

            - task: Docker@2
              displayName: Push image
              inputs:
                repository:  $(acrRepo)
                command: push
                Dockerfile: $(dockerFilePath)
                containerRegistry:  $(acrServiceConnection)
                tags: $(Build.BuildId)

            - task: Docker@2
              displayName: Logout from ACR
              condition: always()
              inputs:
                command: logout
                containerRegistry:  $(acrServiceConnection)    


            

